import { PublicAlias } from './eburon-types';

export const DEFAULT_ALIAS_ID = 'echo-v1.0';
export const DEFAULT_ALIAS_NAME = 'echo';
export const DEFAULT_ALIAS_VERSION = 'v1.0';

export const PUBLIC_ALIAS_CATALOG: PublicAlias[] = [
  {
    alias_id: 'orbit-v3.2',
    alias_name: 'orbit',
    alias_version: 'v3.2',
    capabilities: [
      'Reasoning: long-context analysis',
      'Reasoning: tool orchestration',
      'Structured output generation',
    ],
    limits: {
      max_context: 128000,
      tokens_per_second: 70,
      max_output: 8192,
    },
    status: 'healthy',
    default_temperature: 0.2,
  },
  {
    alias_id: 'codemax-v2.4',
    alias_name: 'codemax',
    alias_version: 'v2.4',
    capabilities: [
      'Code: repo-aware edits',
      'Code: patch generation',
      'Code: refactor planning',
    ],
    limits: {
      max_context: 256000,
      tokens_per_second: 50,
      max_output: 8192,
    },
    status: 'healthy',
    default_temperature: 0.1,
  },
  {
    alias_id: 'vision-v1.1',
    alias_name: 'vision',
    alias_version: 'v1.1',
    capabilities: [
      'Vision: image understanding',
      'Vision: OCR-like extraction',
      'Vision: chart interpretation',
    ],
    limits: {
      max_context: 64000,
      tokens_per_second: 40,
      max_output: 4096,
    },
    status: 'healthy',
    default_temperature: 0.2,
  },
  {
    alias_id: 'echo-v1.0',
    alias_name: 'echo',
    alias_version: 'v1.0',
    capabilities: [
      'Audio: speech-to-text',
      'Audio: text-to-speech',
      'Audio: live turn-taking',
    ],
    limits: {
      max_context: 64000,
      tokens_per_second: 35,
      max_output: 4096,
    },
    status: 'healthy',
    default_temperature: 0.3,
  },
];

export const DEFAULT_VOICE = 'Charon';
export const DEFAULT_VOICE_STAFF = 'Orus';
export const DEFAULT_VOICE_GUEST = 'Charon';

export const AVAILABLE_VOICES: { name: string; value: string }[] = [
  { name: 'Gold', value: 'Zephyr' },
  { name: 'Platinum', value: 'Puck' },
  { name: 'Silver', value: 'Charon' },
  { name: 'Palladium', value: 'Luna' },
  { name: 'Diamond', value: 'Nova' },
  { name: 'Rhodium', value: 'Kore' },
  { name: 'Iridium', value: 'Fenrir' },
  { name: 'Osmium', value: 'Leda' },
  { name: 'Ruthenium', value: 'Orus' },
  { name: 'Sapphire', value: 'Aoede' },
  { name: 'Ruby', value: 'Callirrhoe' },
  { name: 'Emerald', value: 'Autonoe' },
  { name: 'Amethyst', value: 'Enceladus' },
  { name: 'Opal', value: 'Iapetus' },
  { name: 'Garnet', value: 'Umbriel' },
  { name: 'Topaz', value: 'Algieba' },
  { name: 'Jade', value: 'Despina' },
  { name: 'Pearl', value: 'Erinome' },
  { name: 'Quartz', value: 'Algenib' },
  { name: 'Obsidian', value: 'Rasalgethi' },
  { name: 'Onyx', value: 'Laomedeia' },
  { name: 'Bronze', value: 'Achernar' },
  { name: 'Copper', value: 'Alnilam' },
  { name: 'Steel', value: 'Schedar' },
  { name: 'Cobalt', value: 'Gacrux' },
  { name: 'Titanium', value: 'Pulcherrima' },
  { name: 'Tungsten', value: 'Achird' },
  { name: 'Nickel', value: 'Zubenelgenubi' },
  { name: 'Chrome', value: 'Vindemiatrix' },
  { name: 'Zinc', value: 'Sadachbia' },
  { name: 'Brass', value: 'Sadaltager' },
  { name: 'Mercury', value: 'Sulafat' },
];

export const AVAILABLE_LANGUAGES: { name: string; value: string }[] = [
  { name: 'Auto Detect', value: 'auto' },
  { name: 'Afrikaans', value: 'Afrikaans' },
  { name: 'Albanian', value: 'Albanian' },
  { name: 'Amharic', value: 'Amharic' },
  { name: 'Arabic', value: 'Arabic' },
  { name: 'Arabic (Moroccan)', value: 'Moroccan Arabic (Darija)' },
  { name: 'Armenian', value: 'Armenian' },
  { name: 'Azerbaijani', value: 'Azerbaijani' },
  { name: 'Basque', value: 'Basque' },
  { name: 'Belarusian', value: 'Belarusian' },
  { name: 'Bengali', value: 'Bengali' },
  { name: 'Bosnian', value: 'Bosnian' },
  { name: 'Bulgarian', value: 'Bulgarian' },
  { name: 'Catalan', value: 'Catalan' },
  { name: 'Cebuano', value: 'Cebuano' },
  { name: 'Chinese (Simplified)', value: 'Chinese (Simplified)' },
  { name: 'Chinese (Traditional)', value: 'Chinese (Traditional)' },
  { name: 'Corsican', value: 'Corsican' },
  { name: 'Croatian', value: 'Croatian' },
  { name: 'Czech', value: 'Czech' },
  { name: 'Danish', value: 'Danish' },
  { name: 'Dutch', value: 'Dutch' },
  { name: 'Dutch (Flemish)', value: 'Dutch (Flemish)' },
  { name: 'English (US)', value: 'English (US)' },
  { name: 'English (UK)', value: 'English (UK)' },
  { name: 'Esperanto', value: 'Esperanto' },
  { name: 'Estonian', value: 'Estonian' },
  { name: 'Finnish', value: 'Finnish' },
  { name: 'French', value: 'French' },
  { name: 'Frisian', value: 'Frisian' },
  { name: 'Galician', value: 'Galician' },
  { name: 'Georgian', value: 'Georgian' },
  { name: 'German', value: 'German' },
  { name: 'Greek', value: 'Greek' },
  { name: 'Gujarati', value: 'Gujarati' },
  { name: 'Haitian Creole', value: 'Haitian Creole' },
  { name: 'Hausa', value: 'Hausa' },
  { name: 'Hawaiian', value: 'Hawaiian' },
  { name: 'Hebrew', value: 'Hebrew' },
  { name: 'Hindi', value: 'Hindi' },
  { name: 'Hmong', value: 'Hmong' },
  { name: 'Hungarian', value: 'Hungarian' },
  { name: 'Icelandic', value: 'Icelandic' },
  { name: 'Igbo', value: 'Igbo' },
  { name: 'Indonesian', value: 'Indonesian' },
  { name: 'Irish', value: 'Irish' },
  { name: 'Italian', value: 'Italian' },
  { name: 'Japanese', value: 'Japanese' },
  { name: 'Javanese', value: 'Javanese' },
  { name: 'Kannada', value: 'Kannada' },
  { name: 'Kazakh', value: 'Kazakh' },
  { name: 'Khmer', value: 'Khmer' },
  { name: 'Kinyarwanda', value: 'Kinyarwanda' },
  { name: 'Korean', value: 'Korean' },
  { name: 'Kurdish', value: 'Kurdish' },
  { name: 'Kyrgyz', value: 'Kyrgyz' },
  { name: 'Lao', value: 'Lao' },
  { name: 'Latin', value: 'Latin' },
  { name: 'Latvian', value: 'Latvian' },
  { name: 'Lithuanian', value: 'Lithuanian' },
  { name: 'Luxembourgish', value: 'Luxembourgish' },
  { name: 'Macedonian', value: 'Macedonian' },
  { name: 'Malagasy', value: 'Malagasy' },
  { name: 'Malay', value: 'Malay' },
  { name: 'Malayalam', value: 'Malayalam' },
  { name: 'Maltese', value: 'Maltese' },
  { name: 'Maori', value: 'Maori' },
  { name: 'Marathi', value: 'Marathi' },
  { name: 'Mongolian', value: 'Mongolian' },
  { name: 'Myanmar (Burmese)', value: 'Myanmar (Burmese)' },
  { name: 'Nepali', value: 'Nepali' },
  { name: 'Norwegian', value: 'Norwegian' },
  { name: 'Nyanja (Chichewa)', value: 'Nyanja (Chichewa)' },
  { name: 'Odia (Oriya)', value: 'Odia (Oriya)' },
  { name: 'Pashto', value: 'Pashto' },
  { name: 'Persian', value: 'Persian' },
  { name: 'Polish', value: 'Polish' },
  { name: 'Portuguese (Portugal)', value: 'Portuguese (Portugal)' },
  { name: 'Portuguese (Brazil)', value: 'Portuguese (Brazil)' },
  { name: 'Punjabi', value: 'Punjabi' },
  { name: 'Romanian', value: 'Romanian' },
  { name: 'Russian', value: 'Russian' },
  { name: 'Samoan', value: 'Samoan' },
  { name: 'Scots Gaelic', value: 'Scots Gaelic' },
  { name: 'Serbian', value: 'Serbian' },
  { name: 'Sesotho', value: 'Sesotho' },
  { name: 'Shona', value: 'Shona' },
  { name: 'Sindhi', value: 'Sindhi' },
  { name: 'Sinhala (Sinhalese)', value: 'Sinhala (Sinhalese)' },
  { name: 'Slovak', value: 'Slovak' },
  { name: 'Slovenian', value: 'Slovenian' },
  { name: 'Somali', value: 'Somali' },
  { name: 'Spanish', value: 'Spanish' },
  { name: 'Sundanese', value: 'Sundanese' },
  { name: 'Swahili', value: 'Swahili' },
  { name: 'Swedish', value: 'Swedish' },
  { name: 'Tagalog (Filipino)', value: 'Tagalog (Filipino)' },
  { name: 'Tajik', value: 'Tajik' },
  { name: 'Tamil', value: 'Tamil' },
  { name: 'Tatar', value: 'Tatar' },
  { name: 'Telugu', value: 'Telugu' },
  { name: 'Thai', value: 'Thai' },
  { name: 'Turkish', value: 'Turkish' },
  { name: 'Turkmen', value: 'Turkmen' },
  { name: 'Ukrainian', value: 'Ukrainian' },
  { name: 'Urdu', value: 'Urdu' },
  { name: 'Uyghur', value: 'Uyghur' },
  { name: 'Uzbek', value: 'Uzbek' },
  { name: 'Vietnamese', value: 'Vietnamese' },
  { name: 'Welsh', value: 'Welsh' },
  { name: 'Xhosa', value: 'Xhosa' },
  { name: 'Yiddish', value: 'Yiddish' },
  { name: 'Yoruba', value: 'Yoruba' },
  { name: 'Zulu', value: 'Zulu' },
];
